### ISSUE TITLE
[feature/nuget] Adjust changelogs

### ISSUE THREAD

**Issue by ermshiperete** [sillsdev/flexbridge#289]
From [code review comment](https://github.com/sillsdev/flexbridge/pull/251#pullrequestreview-346070187) in #251:

> We have been keeping a changelog for flexbridge for many years in debian/changelog and we have build scripts in this repository that have been used to keep this as well as some public documentation up to date.

The build scripts etc should be changed to take the changes from `CHANGELOG.md` and update `debian/changelog` and the documentation etc.

**Comment by marksvc** [comment]
Support to be able to do this was proposed in https://github.com/sillsdev/SIL.BuildTasks/pull/40
