### ISSUE TITLE
Cannot build with mono 5

### ISSUE THREAD

**Issue by marksvc** [sillsdev/flexbridge#318]
Building FW+FB in flatpak will be easier if I can build both with the same mono version. I need to use mono 5 to build FW. Building FB with mono5-sil (5.16.0.1) results in an error:

> flexbridge/build$ ../run-in-environ msbuild FLExBridge.proj /p:Configuration=Debug
> Microsoft (R) Build Engine version 15.1.8.0 ( Wed Sep  5 19:27:37 UTC 2018) for Mono
> ...
> RunGitVersion:
>   mono "/home/vagrant/fwrepo/flexbridge/packages/GitVersion.MsBuild/tools/net48/gitversion.exe" "/home/vagrant/fwrepo/flexbridge/build" -output file -outputfile gitversion.json
> ...
>     ERROR [06/07/21 9:19:07:53] An unexpected error occurred:
>   System.TypeInitializationException: The type initializer for 'System.Text.Json.JsonSerializerOptions' threw an exception. ---> System.TypeInitializationException: The type initializer for 'System.Text.Json.Serialization.Converters.IEnumerableConverterFactory' threw an exception. ---> System.TypeLoadException: Could not find method '.ctor' due to a type load error: Type System.Text.Json.Serialization.Converters.IDictionaryConverter`1[TCollection] has invalid vtable method slot 32 with method none assembly:/home/vagrant/fwrepo/flexbridge/packages/GitVersion.MsBuild/tools/net48/System.Text.Json.dll type:IDictionaryConverter`1 member:(null)
>      --- End of inner exception stack trace ---
>     at System.Text.Json.JsonSerializerOptions..cctor () [0x0001f] in <74da783969ef4b53bcddcbb5f10fc069>:0 
>      --- End of inner exception stack trace ---
>     at GitVersion.OutputVariables.VersionVariables.JsonSerializerOptions () [0x00000] in <b585ab47eeea455290340bc490899522>:0 

This is not a problem if I use `msbuild FLExBridge.proj  /p:Configuration=Debug` with mono 6.

OS: Ubuntu 20.04
Branch: feature/nuget

Maybe there is a work-around where I can skip using gitversion?

**Comment by ermshiperete** [comment]
Can't you build with mono 6 (and use mono 5 for executing)? 

Otherwise you could pass `/p:DisableGitVersionTask=true` to msbuild. This means it won't set the version in the assemblies. If you still want to have the versions (which might be beneficial for bug reports and troubleshooting) you could install the GitVersion command line tool (I think that's GitVersion.CommandLine) and run: `dotnet gitversion -EnsureAssemblyInfo -UpdateAssemblyInfo`

**Comment by marksvc** [comment]
Thank you. I found DisableGitVersionTask at https://github.com/GitTools/GitVersion/pull/1724 but it does not seem to have any effect 

For example, 
```bash
flexbridge/build$ ../run-in-environ msbuild FLExBridge.proj  /p:Configuration=Debug /p:DisableGitVersionTask=true
```
still runs target `RunGitVersion`. Does this look like I'm not using it correctly?

I tried overriding the target with a no-op `RunGitVersion` target in FLExBridge.proj, which helps the build get started, but later .csproj files end up calling the real RunGitVersion and fail. 

I am able to overwrite the packages/GitVersion.MsBuild/tools/net48/gitversion.exe file and a possible work-around would be to replace it with an assembly that does nothing, or that writes the required gitversion.json file. 

It might be that GitVersion could be modified to work with mono 5, but they might not be excited to support that older mono version. 

> Can't you build with mono 6 (and use mono 5 for executing)?

Yes. It wasn't trivial to get mono 5 installed and usable by Flexbridge and FieldWorks in the different environment (flatpak, /app), so I'm not eager to get a working parallel mono 6 available for running gitversion.exe and teach Flexbridge to use it. But it should be technically possible. Hmm.

**Comment by ermshiperete** [comment]
`FLExBridge.proj` uses the `MsBuild` task to do the actual builds. Did you add `DisableGitVersionTask` to the list of passed in properties?

```
<MSBuild Projects="$(RootDir)/$(Solution)" Targets="Build" Properties="Configuration=$(Configuration);GetVersion=$(GetVersion);WriteVersionInfoToBuildLog=$(WriteVersionInfoToBuildLog);DisableGitVersionTask=$(DisableGitVersionTask)"/>
```

(MSBuild appears multiple times in `FLExBridge.proj`)

**Comment by marksvc** [comment]
Thank you @ermshiperete . I learned from https://github.com/GitTools/GitVersion/issues/2640 that I also needed to upgrade GitVersion.MsBuild to 5.6.9. Now I can build with mono5-sil with a command like

```bash
build$ ../run-in-environ msbuild FLExBridge.proj -p:Configuration=Debug /p:DisableGitVersionTask=true /p:GitVersion_SemVer=1.2.3 /p:Version=1.2.3
```
