### ISSUE TITLE
Master branch building from FlexBridgeBeta depenendencies

### ISSUE THREAD

**Issue by darcywong00** [sillsdev/flexbridge#8]
FLEx Bridge-master-Win32-Continuous is currently failing at unit test on TeamCity.

The test runs fine locally on my developer machine, where dependencies are gathered via UpdateDependencies.bat.

When I reviewed Download.targets which TC uses, it seems the dependencies are being pulled from the FlexBridgeBeta Continuous builds.

The reason the unit test is failing now is because we recently added STRONG_NAME on the master branch of libpalaso, and the failing unit tests are flagging the error:
"Could not load file or assembly 'Palaso.TestUtilities, Version=2.5.120.0, Culture=neutral, PublicKeyToken=cab3c8c5232dfcf2' or one of its dependencies"

Should Download.targets be deprecated and let TC manage the dependencies?

**Comment by regnrand** [comment]
I fixed up the Team City build dependencies to not use the strong named builds of Palaso and Chorus, as well as revised files in the FLEx Bridge repo. "Download.targets" was one piece of the puzzle, and it is no more.
